[package]
name = "local-mpris"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
mpris = "2.0.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
symphonia = { version = "0.5.5", features = ["all-codecs"] }
